<?php
/**
 * Database Configuration & PDO Connection
 * Class Routine Management System - NasimSoft
 * Generated by Installer
 */

if (!defined('CRMS_SYSTEM')) {
    define('CRMS_SYSTEM', true);
}

define('DB_HOST', 'localhost');
define('DB_NAME', 'juioikko_class_routine_system');
define('DB_USER', 'juioikko_class_routine_system');
define('DB_PASS', '01990166355nN@');
define('DB_CHARSET', 'utf8mb4');

function getDB(): PDO
{
    static $pdo = null;
    if ($pdo === null) {
        $dsn = 'mysql:host=' . DB_HOST . ';dbname=' . DB_NAME . ';charset=' . DB_CHARSET;
        $options = [
            PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
            PDO::ATTR_EMULATE_PREPARES   => false,
            PDO::ATTR_PERSISTENT         => false,
            PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci"
        ];
        try {
            $pdo = new PDO($dsn, DB_USER, DB_PASS, $options);
        } catch (PDOException $e) {
            die('Database Connection Error: ' . $e->getMessage());
        }
    }
    return $pdo;
}

function testDBConnection(): bool
{
    try {
        $pdo = getDB();
        $pdo->query('SELECT 1');
        return true;
    } catch (Exception $e) {
        return false;
    }
}

// Add at the bottom of config/database.php:
class Database {
    public static function getInstance(): PDO {
        return getDB();
    }
}